---
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.type: single-node

## X-Pack
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
