version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.0.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms7g -Xmx7g"
      ELASTIC_PASSWORD: password
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.0.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5624:5624"
      - "5000:5000"
      - "9600:9600"
    environment:
        LS_JAVA_OPTS: "-Xms2g -Xmx2g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.0.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5621:5621"
    networks:
      - elk
    depends_on:
      - elasticsearch

  reverseproxy:
    build:
      context: nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5622:5622"
    networks:
      - elk
    restart: always

networks:

  elk:
    driver: bridge
